Singlestore jdbc: Quarkus native support
quarkiverse/quarkus-jdbc-singlestore pull request #3
Opened 2024-10-21 13:07 UTC by Hemantkumar-Chigadani

2024-10-21 13:13 UTC, Hemantkumar-Chigadani commented
> Please revert the changes in the following files:
> 
> * `.github/workflows/*`
> * `.github/project.yml`

@gastaldi Sure, I can but these files are generated (default) by extension command expect `.github/project.yml` which I had updated.

2024-10-21 13:15 UTC, gastaldi commented
Also you need to accept the invitation to join the Organization, I see the invitation is still pending

2024-10-21 13:21 UTC, Hemantkumar-Chigadani commented
> Also you need to accept the invitation to join the Organization, I see the invitation is still pending

Just now accepted it, sorry I did not receive an email notification on this topic so did not notice until you mention it, Cheers

2024-10-21 13:27 UTC, gastaldi commented on runtime/src/main/resources/META-INF/quarkus-extension.yaml
> +  status: "stable"
I'd recommend starting with a preview status since it's pretty recent
```suggestion
  status: "preview"
```

2024-10-21 13:27 UTC, gastaldi commented on runtime/src/main/resources/META-INF/quarkus-extension.yaml
> +  guide: "https://quarkus.io/guides/datasource"
```suggestion
  guide: "https://docs.quarkiverse.io/quarkus-jdbc-singlestore/dev/"
```

2024-10-21 19:07 UTC, melloware requested changes

2024-10-21 19:07 UTC, melloware commented on runtime/src/main/resources/META-INF/quarkus-extension.yaml
> +  guide: "https://docs.quarkiverse.io/quarkus-jdbc-singlestore/dev/"
```suggestion
  guide: "https://docs.quarkiverse.io/quarkus-jdbc-singlestore/dev/"
  icon-url: "https://upload.wikimedia.org/wikipedia/en/f/f1/SingleStore_logo.png"
```

2024-10-22 11:14 UTC, gastaldi approved these changes

2024-10-22 11:25 UTC, gastaldi commented
@Hemantkumar-Chigadani when you feel it's ready go ahead and merge your first PR 😉

2024-10-22 13:33 UTC, merged

2024-10-22 13:38 UTC, melloware commented
@Hemantkumar-Chigadani you should work on the README.MD next.

2024-10-22 13:59 UTC, Hemantkumar-Chigadani commented
> @Hemantkumar-Chigadani you should work on the README.MD next.

@melloware Its one of my todo list, thanks for reminding me anyway, cheers

2024-10-22 14:11 UTC, gastaldi commented
@all-contributors add @Hemantkumar-Chigadani for code and maintenance

2024-10-22 14:14 UTC, gastaldi commented
@all-contributors add @melloware for review

2024-10-22 14:18 UTC, gastaldi commented
> > @Hemantkumar-Chigadani you should work on the README.MD next.
> 
> @melloware Its one of my todo list, thanks for reminding me anyway, cheers

@Hemantkumar-Chigadani feel free to create issues in this repository to make sure your TODO list is completed ;)